name: Update Markdown Placeholders

on:
  pull_request:
    branches:
      - main

jobs:
  update-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update placeholders in markdown files
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          REPO_URL="https://github.com/$GITHUB_REPOSITORY"

          find ./docs -type f -name "*.md" -exec sed -i "s/{{REPOSITORY_NAME}}/$REPO_NAME/g" {} \;
          find ./docs -type f -name "*.md" -exec sed -i "s|{{REPOSITORY_URL}}|$REPO_URL|g" {} \;

          if git diff --quiet ./docs; then
            echo "No files have been updated."
          else
            echo "Files have been updated."
            echo "CHANGES_MADE=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.CHANGES_MADE == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

          git add ./docs/*.md
          git commit -m 'Update markdown placeholders'

          git fetch origin
          git rebase origin/${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}